### ISSUE TITLE
The timm library is throwing an error.

### ISSUE THREAD

**Issue by imskyszy** [MichaelLynn1996/AAT#1]
from timm.layers import use_fused_attn, apply_rot_embed_cat
from timm.models.layers import to_2tuple,trunc_normal_, Mlp
from timm.models.vision_transformer import Attention, LayerScale, DropPath
The functions use_fused_attn, apply_rot_embed_cat, Mlp, and LayerScale cannot be found in the library.
How to solve the problem.
thanks

**Comment by MichaelLynn1996** [comment]
Sorry for the late reply.

This issue seems to be related to the timm version.
I made some adjustments to the [ast](https://github.com/YuanGongND/ast) source code to accommodate the latest version of timm at that time. I've checked my environment, and I'm using version `timm==0.9.12`.
I will update the _requirements.txt_ when I have some free time.
Hope this helps.

**Comment by MichaelLynn1996** [comment]
> from timm.layers import use_fused_attn, apply_rot_embed_cat from timm.models.layers import to_2tuple,trunc_normal_, Mlp from timm.models.vision_transformer import Attention, LayerScale, DropPath The functions use_fused_attn, apply_rot_embed_cat, Mlp, and LayerScale cannot be found in the library. How to solve the problem. thanks

Sorry for the late reply.

This issue seems to be related to the timm version.
I made some adjustments to the [ast](https://github.com/YuanGongND/ast) source code to accommodate the latest version of timm at that time. I've checked my environment, and I'm using version `timm==0.9.12`.
I will update the requirements.txt when I have some free time.
Hope this helps.

**Comment by imskyszy** [comment]
I have successfully replaced and solved the problem. Thank you very much for your response
